### ISSUE TITLE
[Bug]: Upgraded to AG2 0.5 and imports broke

### ISSUE THREAD

**Issue by bassilkhilo** [ag2ai/ag2#169]
### Describe the bug

Upgraded to v0.5 and I no longer can import 

from autogen import (
    SwarmResult,
    AssistantAgent,
    SwarmAgent,
)

I cannot even import 

from autogen.coding import DockerCommandLineCodeExecutor

Not sure what happened. 

### Steps to reproduce

Upgrade from 0.41 to 0.5 via pip install ag2 --upgrade

**Comment by Hk669** [comment]
cc @marklysze

**Comment by marklysze** [comment]
@bassilkhilo, are you able to output the trace when you try and run the program? Just checking if, perhaps, there are any changes made to other files?

**Comment by ashim-mahara** [comment]
using `pyautogen`works.

**Comment by ohdearquant** [comment]
@marklysze some small inconsistency here: 

```
      - name: Build pyautogen
        shell: pwsh
        run: |
          pip install twine
          python setup.py sdist bdist_wheel
      - name: Publish pyautogen to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYAUTOGEN_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYAUTOGEN_PYPI_PASSWORD }}
        shell: pwsh
        run: twine upload dist/*pyautogen*
      - name: Build autogen
        shell: pwsh
        run: |
          python setup_autogen.py sdist bdist_wheel
      - name: Publish autogen to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.AUTOGEN_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.AUTOGEN_PYPI_PASSWORD }}
        shell: pwsh
        run: twine upload dist/autogen*
      - name: Build ag2
        shell: pwsh
        run: |
          python setup_ag2.py sdist bdist_wheel
      - name: Publish ag2 to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.AUTOGEN_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.AUTOGEN_PYPI_PASSWORD }}
        shell: pwsh
        run: twine upload dist/ag2*

```

could this be it?
