### ISSUE TITLE
[Issue]: Please simplify the agent/function/groupchat creation process

### ISSUE THREAD

**Issue by tyler-suard-parker** [ag2ai/ag2#439]
### Describe the issue

Hello.  I am trying to create a script that will allow anyone in my company to easily create an agent-based search function, just by passing in the address of the search API.  That is proving to be super difficult.  I have to:

1. Create the assistant and userproxy agent
2. Give them specific instructions about that search function
3. Add the search function to an LLM config
4. Add the @register decorators to the search function
5. Add the 2 agents to a groupchat so the search is asynchronous and non-blocking with the other agents
6. Create a group chat manager
7. Give the group chat manager instructions

It would be awesome if there was a way to simplify this whole process.  Like one line to create the assistant and userproxy agent and assign them a function (similar to what OpenAI Swarm does), Create a groupchat and manager in one line, etc.

**Comment by marklysze** [comment]
Thanks @tyler-suard-parker, would you be able to put a sample code block that you'd like to see?

**Comment by tyler-suard-parker** [comment]
@marklysze Sure, thank you for asking.

def search(query):
    return "This is an example search result"

search_agent = create_agent()

add_function_to_agent(function = search, agent = search_agent)

writer_agent = create_agent("You are a writer")

groupchat = add_agents_to_groupchat(search_agent, writer_agent)

groupchat.start("Please search for information about cats and write an essay.")

**Comment by tyler-suard-parker** [comment]
This is simpler, because instead of requiring 2 agents (userproxy and assistant) to use a search function, it only needs one agent that can both generate queries and call the search function.  Also the groupchat does not need a manager in this case.  Many of the parameters currently used for creating agents are abstracted away.

**Comment by tyler-suard-parker** [comment]
Here is another suggestion, creating agent workflows from a .yaml file:

``` 
- LLM configuration: llm_config.py

- Agents:
  - Agent: 
    - Name: SearchAgent
    - Type: AssistantAgent
    - Prompt: You are an expert on San Francisco.
  - Agent:
    - Name: SearchExecutorAgent
    - Type: UserProxyAgent
    - Prompt: Reply with "TERMINATE" when the task is complete.

- GroupChats:
  - GroupChat:
    - Name: SearchGroupChat
    - Agents:
      - SearchAgent
      - SearchExecutorAgent

- Conversations:
  - Conversation:
    - GroupChat: SearchGroupChat
    - First message: Search for the best restaurants in San Francisco.
```
